# -*- coding: utf-8 -*-
"""2a_neuroimaging_smri_baseline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UIXUD2jWGgGdrL7ufgXxvN6ITXiXHDs
"""

import os
import glob
import subprocess
import numpy as np
import concurrent.futures
import ants
import SimpleITK as sitk


# 1. CONFIGURATION

INPUT_DIR = './data/nifti_mri_raw'
OUTPUT_DIR = './data/dl_ready_baseline_mri'

TARGET_SHAPE = (128, 128, 128)
MAX_WORKERS = 4

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Pre-load MNI152 template into memory
print("Loading standard MNI152 template...")
mni_template = ants.image_read(ants.get_ants_data('mni'))


# 2. HELPER FUNCTIONS
def run_synthstrip(input_path, output_dir):
    """ FreeSurfer SynthStrip via Docker ."""
    filename = os.path.basename(input_path)
    out_brain = os.path.join(output_dir, filename.replace('.nii', '_brain.nii'))
    out_mask = os.path.join(output_dir, filename.replace('.nii', '_mask.nii'))

    cmd = [
        'docker', 'run', '--rm',
        '-v', f"{os.path.abspath(INPUT_DIR)}:/input",
        '-v', f"{os.path.abspath(output_dir)}:/output",
        'freesurfer/synthstrip',
        '-i', f"/input/{os.path.relpath(input_path, INPUT_DIR)}",
        '-o', f"/output/{os.path.basename(out_brain)}",
        '-m', f"/output/{os.path.basename(out_mask)}"
    ]

    try:
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        return out_brain, out_mask
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"SynthStrip Error on {filename}: {e.stderr.decode('utf-8')}")

def run_n4_correction(stripped_path):
    """ N4 Bias Field Correction using SimpleITK"""
    out_n4 = stripped_path.replace('_brain.nii', '_brain_n4.nii')

    input_image = sitk.ReadImage(stripped_path, sitk.sitkFloat32)
    mask_image = sitk.OtsuThreshold(input_image, 0, 1, 200)

    corrector = sitk.N4BiasFieldCorrectionImageFilter()
    corrected_image = corrector.Execute(input_image, mask_image)

    sitk.WriteImage(corrected_image, out_n4)
    return out_n4

def z_score_normalize(img_array, mask_array):
    """Z-score intensity normalization."""
    mask = mask_array > 0
    if not np.any(mask):
        return img_array

    mean_val = np.mean(img_array[mask])
    std_val = np.std(img_array[mask])

    img_array[mask] = (img_array[mask] - mean_val) / (std_val + 1e-8)
    img_array[~mask] = 0.0 # Ensure background remains exactly 0
    return img_array

# 3. CORE PROCESSING PIPELINE
def process_baseline_smri(patno_dir):
    """Executes the affine registration and Z-scoring pipeline for unimodal sMRI."""
    patno = os.path.basename(patno_dir)
    out_tensor_path = os.path.join(OUTPUT_DIR, f"{patno}_baseline_smri.npy")

    if os.path.exists(out_tensor_path):
        return f"Skipping {patno}: Already processed."

    try:
        # Find raw T1w NIfTI file
        smri_path = glob.glob(os.path.join(patno_dir, '*_T1w.nii*'))[0]

        # Temp dir for intermediate files
        temp_dir = os.path.join(OUTPUT_DIR, "temp", patno)
        os.makedirs(temp_dir, exist_ok=True)

        # Step 1: FreeSurfer SynthStrip
        stripped_path, mask_path = run_synthstrip(smri_path, temp_dir)

        # Step 2: N4 Bias Field Correction
        n4_path = run_n4_correction(stripped_path)

        # Step 3: Spatial Normalization to MNI152 using Affine
        smri_img = ants.image_read(n4_path)
        smri_mask = ants.image_read(mask_path)

        registration = ants.registration(fixed=mni_template, moving=smri_img, type_of_transform='Affine')
        smri_aligned = registration['warpedmovout']

        # Apply the exact same affine transform to the brain mask to keep them aligned
        mask_aligned = ants.apply_transforms(fixed=mni_template, moving=smri_mask, transformlist=registration['fwdtransforms'], interpolator='nearestNeighbor')

        # Step 4: Resample to isotropic target shape (128x128x128)
        smri_resampled = ants.resample_image(smri_aligned, TARGET_SHAPE, use_voxels=True, interp_type=1)
        mask_resampled = ants.resample_image(mask_aligned, TARGET_SHAPE, use_voxels=True, interp_type=1)

        # Step 5: Z-Score Normalization inside the mask
        normalized_array = z_score_normalize(smri_resampled.numpy(), mask_resampled.numpy())

        # Format as (1, D, H, W) for PyTorch Conv3d
        final_tensor = np.expand_dims(normalized_array, axis=0)
        np.save(out_tensor_path, final_tensor)

        return f"Successfully processed baseline sMRI for PATNO: {patno}"

    except Exception as e:
        return f"Error processing PATNO {patno}: {str(e)}"


# 4. EXECUTION

if __name__ == '__main__'

    patno_dirs = [os.path.join(INPUT_DIR, d) for d in os.listdir(INPUT_DIR) if os.path.isdir(os.path.join(INPUT_DIR, d))]
    print(f"Found {len(patno_dirs)} subject directories.")

    with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        results = executor.map(process_baseline_smri, patno_dirs)
        for result in results:
            print(result)

    print(" BASELINE sMRI PIPELINE COMPLETE")