# -*- coding: utf-8 -*-
"""2b_neuroimaging_early_fusion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UIXUD2jWGgGdrL7ufgXxvN6ITXiXHDs
"""

import os
import glob
import numpy as np
import concurrent.futures
import ants
import antspynet
import SimpleITK as sitk
from dipy.io.image import load_nifti
from dipy.io.gradients import read_bvals_bvecs
from dipy.core.gradients import gradient_table
import dipy.reconst.dti as dti
import nibabel as nib


# 1. CONFIGURATION
INPUT_DIR = './data/nifti_mri+dti_raw'
OUTPUT_DIR = './data/dl_ready_fused_tensors'

TARGET_SHAPE = (128, 128, 128)
MAX_WORKERS = 4

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Pre-load MNI152 template into memory
print("Loading standard MNI152 template...")
mni_template = ants.image_read(ants.get_ants_data('mni'))


# 2. HELPER FUNCTIONS
def run_n4_correction(input_path, out_path):
    """Applies N4 Bias Field Correction using SimpleITK ."""
    input_image = sitk.ReadImage(input_path, sitk.sitkFloat32)

    # Create a basic mask (background is 0) using Otsu to bound the N4 algorithm
    mask_image = sitk.OtsuThreshold(input_image, 0, 1, 200)

    # Apply N4 Correction
    corrector = sitk.N4BiasFieldCorrectionImageFilter()
    corrected_image = corrector.Execute(input_image, mask_image)

    sitk.WriteImage(corrected_image, out_path)
    return out_path

def compute_fa_map(dwi_path, bval_path, bvec_path, out_fa_path):
    """ diffusion tensor model using DIPY , outputs FA map."""
    data, affine, img = load_nifti(dwi_path, return_img=True)
    bvals, bvecs = read_bvals_bvecs(bval_path, bvec_path)
    gtab = gradient_table(bvals, bvecs)

    tenmodel = dti.TensorModel(gtab)
    tenfit = tenmodel.fit(data)
    fa_map = tenfit.fa

    # Save temporarily to be loaded by ANTs
    fa_img = nib.Nifti1Image(fa_map.astype(np.float32), affine)
    nib.save(fa_img, out_fa_path)
    return out_fa_path

def min_max_normalize(img_array):
    """Independent Min-Max intensity normalization (0 to 1)"""
    mask = img_array > 0
    if not np.any(mask):
        return img_array

    min_val = np.min(img_array[mask])
    max_val = np.max(img_array[mask])

    img_array[mask] = (img_array[mask] - min_val) / (max_val - min_val + 1e-8)
    img_array[~mask] = 0.0 # Ensure background remains 0
    return img_array


# 3. CORE PROCESSING PIPELINE
def process_trimodal_subject(patno_dir):
    """Executes the strict co-registration and early fusion pipeline for a single subject."""
    patno = os.path.basename(patno_dir)
    out_tensor_path = os.path.join(OUTPUT_DIR, f"{patno}_fused_mri_dti.npy")

    if os.path.exists(out_tensor_path):
        return f"Skipping {patno}: Already processed."

    try:
        # File discovery
        smri_path = glob.glob(os.path.join(patno_dir, '*_T1w.nii*'))[0]
        dwi_path = glob.glob(os.path.join(patno_dir, '*_dwi.nii*'))[0]
        bval_path = glob.glob(os.path.join(patno_dir, '*_dwi.bval'))[0]
        bvec_path = glob.glob(os.path.join(patno_dir, '*_dwi.bvec'))[0]

        # Step 1: N4 Bias Field Correction on Raw sMRI
        temp_n4_path = os.path.join(patno_dir, f"{patno}_temp_n4.nii.gz")
        run_n4_correction(smri_path, temp_n4_path)

        # Step 2: Compute FA Map via DIPY
        temp_fa_path = os.path.join(patno_dir, f"{patno}_temp_FA.nii.gz")
        compute_fa_map(dwi_path, bval_path, bvec_path, temp_fa_path)

        # Step 3: Spatial Co-Registration
        smri_img = ants.image_read(temp_n4_path)
        fa_img = ants.image_read(temp_fa_path)

        # 3a. Register N4-corrected sMRI to MNI152 using SyN
        smri_reg = ants.registration(fixed=mni_template, moving=smri_img, type_of_transform='SyN')
        smri_mni = smri_reg['warpedmovout']

        # 3b. Co-register FA map directly to the MNI-aligned sMRI using Affine
        fa_reg = ants.registration(fixed=smri_mni, moving=fa_img, type_of_transform='Affine')
        fa_aligned = fa_reg['warpedmovout']

        # Step 4: Skull-Stripping using antspyne
        prob_mask = antspynet.brain_extraction(smri_mni, modality='t1')
        binary_mask = ants.threshold_image(prob_mask, low_thresh=0.5, high_thresh=1.0, inval=1, outval=0)

        smri_stripped = ants.mask_image(smri_mni, binary_mask)
        fa_stripped = ants.mask_image(fa_aligned, binary_mask)

        # Step 5: Resample to isotropic target shape (128x128x128)
        smri_resampled = ants.resample_image(smri_stripped, TARGET_SHAPE, use_voxels=True, interp_type=1)
        fa_resampled = ants.resample_image(fa_stripped, TARGET_SHAPE, use_voxels=True, interp_type=1)

        # Step 6: Independent Min-Max Normalization
        smri_norm = min_max_normalize(smri_resampled.numpy())
        fa_norm = min_max_normalize(fa_resampled.numpy())

        # Step 7: Pixel-Level Early Fusion
        # Output shape: (2, 128, 128, 128)
        fused_tensor = np.stack([smri_norm, fa_norm], axis=0)
        np.save(out_tensor_path, fused_tensor)

        # Cleanup temporary files to save GCP disk space
        os.remove(temp_n4_path)
        os.remove(temp_fa_path)

        return f"Successfully processed and fused PATNO: {patno}"

    except Exception as e:
        return f"Error processing PATNO {patno}: {str(e)}"

# 4. EXECUTION
if __name__ == '__main__':
    print(" STARTING NEUROIMAGING EARLY FUSION PIPELINE ")

    # Identify all patient directories containing paired data
    patno_dirs = [os.path.join(INPUT_DIR, d) for d in os.listdir(INPUT_DIR) if os.path.isdir(os.path.join(INPUT_DIR, d))]
    print(f"Found {len(patno_dirs)} subject directories. Initiating strict MNI SyN+Affine co-registration...")

    # Process concurrently (Ensure GCP VM has sufficient RAM for multiple ANTs SyN executions)
    with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        results = executor.map(process_trimodal_subject, patno_dirs)
        for result in results:
            print(result)

    print("NEUROIMAGING PIPELINE (FUSED) COMPLETE ")