# -*- coding: utf-8 -*-
"""3_cagf_architectures

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UIXUD2jWGgGdrL7ufgXxvN6ITXiXHDs
"""

import torch
import torch.nn as nn
from torchvision.models.video import r3d_18

# 1. GENETIC TRANSFORMER ENCODER
class GeneticTransformer(nn.Module):
    def __init__(self, num_snps=100, patch_size=10, d_model=64, nhead=8, num_layers=1, num_classes=3):
        super().__init__()
        self.patch_size = patch_size
        self.seq_len = num_snps // patch_size

        self.embedding = nn.Linear(self.patch_size, d_model)
        self.pos_encoder = nn.Parameter(torch.randn(1, self.seq_len, d_model))

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=nhead, dim_feedforward=256,
            batch_first=True, dropout=0.3
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        self.flatten_dim = self.seq_len * d_model
        self.feature_extractor = nn.Linear(self.flatten_dim, 512)

    def forward(self, x):
        batch_size = x.size(0)
        x = x.view(batch_size, self.seq_len, self.patch_size)
        x = self.embedding(x) + self.pos_encoder
        x = self.transformer(x)
        x = x.flatten(start_dim=1)
        return self.feature_extractor(x) # Returns 512-dim feature vector


# 2. 3D RESNET-18 SPATIAL ENCODER
class MedicalNetFeatureExtractor(nn.Module):
    def __init__(self, weights_path=None):
        super().__init__()
        self.model = r3d_18(weights=None)

        # Load Pre-trained weights if provided
        if weights_path:
            state_dict = torch.load(weights_path, map_location='cpu')
            if 'state_dict' in state_dict: state_dict = state_dict['state_dict']
            clean_dict = {k.replace('module.', ''): v for k, v in state_dict.items()}
            self.model.load_state_dict(clean_dict, strict=False)

        # Modify Conv1 for 2 channels (sMRI + DTI)
        old_conv = self.model.stem[0]
        new_conv = nn.Conv3d(2, old_conv.out_channels, kernel_size=old_conv.kernel_size,
                             stride=old_conv.stride, padding=old_conv.padding, bias=False)

        with torch.no_grad():
            averaged_weights = old_conv.weight.mean(dim=1, keepdim=True)
            new_conv.weight[:, 0:1, :, :, :] = averaged_weights
            new_conv.weight[:, 1:2, :, :, :] = averaged_weights

        self.model.stem[0] = new_conv
        self.model.fc = nn.Identity() # Output 512 dims

        for param in self.model.stem.parameters(): param.requires_grad = False
        for param in self.model.layer1.parameters(): param.requires_grad = False
        for param in self.model.layer2.parameters(): param.requires_grad = False

    def forward(self, x):
        return self.model(x)


# 3. CAGF-NET FUSION MODULE
class CAGFNet(nn.Module):
    def __init__(self, feature_dim=512, num_heads=8, num_classes=3):
        super().__init__()

        # Projection Blocks
        self.proj_img = nn.Sequential(nn.Linear(feature_dim, feature_dim), nn.LayerNorm(feature_dim), nn.GELU())
        self.proj_gene = nn.Sequential(nn.Linear(feature_dim, feature_dim), nn.LayerNorm(feature_dim), nn.GELU())

        # Bi-directional Attention
        self.attn_img_query = nn.MultiheadAttention(embed_dim=feature_dim, num_heads=num_heads, batch_first=True, dropout=0.2)
        self.attn_gene_query = nn.MultiheadAttention(embed_dim=feature_dim, num_heads=num_heads, batch_first=True, dropout=0.2)

        self.norm_img = nn.LayerNorm(feature_dim)
        self.norm_gene = nn.LayerNorm(feature_dim)

        # Adaptive Gating MLP
        self.gate_network = nn.Sequential(
            nn.Linear(feature_dim * 2, 256),
            nn.BatchNorm1d(256),
            nn.Tanh(),
            nn.Linear(256, 2),
            nn.Softmax(dim=1)
        )

        # Classifier
        self.classifier = nn.Sequential(
            nn.Linear(feature_dim, 256), nn.BatchNorm1d(256), nn.GELU(), nn.Dropout(0.4),
            nn.Linear(256, 64), nn.GELU(), nn.Dropout(0.2),
            nn.Linear(64, num_classes)
        )

    def forward(self, x_img, x_gene):
        # 1. Parallel Projections (P_img, P_gene)
        p_img = self.proj_img(x_img).unsqueeze(1)
        p_gene = self.proj_gene(x_gene).unsqueeze(1)

        # 2. Image-Query Attention & Gene-Query Attention
        attn_img, _ = self.attn_img_query(query=p_img, key=p_gene, value=p_gene)
        attn_gene, _ = self.attn_gene_query(query=p_gene, key=p_img, value=p_img)

        # 3. Residual Addition + LayerNorm (Out_img, Out_gene)
        out_img = self.norm_img(p_img + attn_img).squeeze(1)
        out_gene = self.norm_gene(p_gene + attn_gene).squeeze(1)

        # 4. Adaptive Gating
        joint_context = torch.cat((out_img, out_gene), dim=1)
        gates = self.gate_network(joint_context)

        # 5. Extract Weights (W_img, W_gene)
        w_img = gates[:, 0:1]
        w_gene = gates[:, 1:2]

        # 6. Intra-interaction Scaling
        weighted_img = out_img * w_img
        weighted_gene = out_gene * w_gene

        # 7. Final Classification (F_512)
        fused_vector = weighted_img + weighted_gene
        predictions = self.classifier(fused_vector)

        return predictions, out_img, out_gene


# 4. GAN ARCHITECTURES
class Generator(nn.Module):
    def __init__(self, latent_dim=100, out_dim=1024):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(latent_dim, 256), nn.BatchNorm1d(256), nn.LeakyReLU(0.2),
            nn.Linear(256, 512), nn.BatchNorm1d(512), nn.LeakyReLU(0.2),
            nn.Linear(512, out_dim), nn.Tanh()
        )
    def forward(self, z): return self.net(z)

class Discriminator(nn.Module):
    def __init__(self, in_dim=1024):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, 512), nn.LeakyReLU(0.2), nn.Dropout(0.3),
            nn.Linear(512, 256), nn.LeakyReLU(0.2), nn.Dropout(0.3),
            nn.Linear(256, 1), nn.Sigmoid()
        )
    def forward(self, x): return self.net(x)