# -*- coding: utf-8 -*-
"""5a_xai_shap_genomics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1I2L63b0tdYV-LO7_5FfSRwq4t-oPu9
"""

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
import torch.nn.functional as F
import shap
import matplotlib.pyplot as plt
import warnings
import os

warnings.filterwarnings('ignore')

from 3_cagf_architectures import GeneticTransformer

# 1. CONFIGURATION
INPUT_CSV = './data/top100snps_by_importance.csv'
MODEL_SAVE_PATH = './results/Genetic_Transformer_XAI.pth'
OUTPUT_DIR = './results/xai_plots'
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Established SNPs to track in the rankings
KNOWN_PD_SNPS = [
    "rs34637584", "rs11264633", "rs2188399", "rs216712", "rs4829854",
    "rs2303822", "rs7309", "rs12668181", "rs16980779", "rs78837745",
    "rs3120900", "rs9897342", "rs2002423", "rs6974322", "rs6004947"
]

class ShapWrapper(nn.Module):
    """Wrapper to output pure logits for SHAP GradientExplainer."""
    def __init__(self, trained_model):
        super().__init__()
        self.model = trained_model
    def forward(self, x):
        return self.model(x)

def run_shap_analysis():
    print("1. LOADING GENOMIC DATA")
    df = pd.read_csv(INPUT_CSV)
    labels = df['Label_Int'].values

    snps_df = df.drop(columns=['PATNO', 'Label_Int']).iloc[:, :100]
    feature_names = snps_df.columns.tolist()
    snps = snps_df.values.astype(np.float32)

    label_map = {val: idx for idx, val in enumerate(np.unique(labels))}
    mapped_labels = np.array([label_map[l] for l in labels])
    class_names = ["HC", "Prodromal", "PD"]

    X_train, X_val, y_train, y_val = train_test_split(snps, mapped_labels, test_size=0.3, random_state=42, stratify=mapped_labels)
    train_loader = DataLoader(TensorDataset(torch.tensor(X_train), torch.tensor(y_train)), batch_size=16, shuffle=True)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = GeneticTransformer(num_snps=100, patch_size=10, num_classes=len(class_names)).to(device)

    # Quick training loop to fit the local explainer model
    print("2. FITTING GENETIC TRANSFORMER")
    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-3)
    criterion = nn.CrossEntropyLoss()

    model.train()
    for epoch in range(20):
        for batch_X, batch_y in train_loader:
            batch_X, batch_y = batch_X.to(device), batch_y.to(device)
            optimizer.zero_grad()
            loss = criterion(model(batch_X), batch_y)
            loss.backward()
            optimizer.step()

    torch.save(model.state_dict(), MODEL_SAVE_PATH)

    print(" 3. EXECUTING SHAP GRADIENT EXPLAINER ")
    wrapped_model = ShapWrapper(model).to(device)
    wrapped_model.eval()

    np.random.seed(42)
    background_tensor = torch.tensor(snps[np.random.choice(snps.shape[0], 100, replace=False)]).to(device)
    test_numpy = snps[np.random.choice(snps.shape[0], 200, replace=False)]
    test_tensor = torch.tensor(test_numpy).to(device)

    explainer = shap.GradientExplainer(wrapped_model, background_tensor)
    shap_values = explainer.shap_values(test_tensor)

    for class_idx, class_name in enumerate(class_names):
        sv = shap_values[class_idx] if isinstance(shap_values, list) else shap_values[:, :, class_idx]
        sv = sv.reshape(test_numpy.shape)

        plt.figure(figsize=(10, 8))
        plt.title(f"Top 20 SNPs driving {class_name}", fontsize=14)
        shap.summary_plot(sv, test_numpy, feature_names=feature_names, max_display=20, show=False)

        save_path = os.path.join(OUTPUT_DIR, f'Shap_Summary_{class_name}.png')
        plt.savefig(save_path, bbox_inches='tight', dpi=300, facecolor='white')
        plt.close()

        # Print rankings for established SNPs
        mean_abs_shap = np.abs(sv).mean(axis=0)
        importance_df = pd.DataFrame({'SNP': feature_names, 'Impact': mean_abs_shap}).sort_values(by='Impact', ascending=False).reset_index(drop=True)
        importance_df['Rank'] = importance_df.index + 1

        print(f"\nFamous SNP Rankings for {class_name}:")
        found = importance_df[importance_df['SNP'].isin(KNOWN_PD_SNPS)]
        if not found.empty:
            print(found[['SNP', 'Rank', 'Impact']].to_string(index=False))
        else:
            print("None found in Top 100.")

    print(f"\n SHAP analysis complete. Plots saved to {OUTPUT_DIR}")

if __name__ == '__main__':
    run_shap_analysis()