# -*- coding: utf-8 -*-
"""5b_xai_gradcam_imaging

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1I2L63b0tdYV-LO7_5FfSRwq4t-oPu9
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import zoom, label
import sys
import gc
import os

from 3_cagf_architectures import MedicalNetFeatureExtractor

# 1. CONFIGURATION

WEIGHTS_PATH = './results/best_medicalnet_extractor.pth'
MRI_PATHS = [
    './data/dl_ready_fused_tensors/3584_fused_mri_dti.npy',
    './data/dl_ready_fused_tensors/3819_fused_mri_dti.npy',
    './data/dl_ready_fused_tensors/3863_fused_mri_dti.npy'
]
OUTPUT_IMG = './results/xai_plots/medicalnet_gradcam_mri_dti_fused.png'
os.makedirs(os.path.dirname(OUTPUT_IMG), exist_ok=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(" 1. LOADING MULTIMODAL MEDICALNET")
net = MedicalNetFeatureExtractor(weights_path=None).to(device)

try:
    # Handle safe loading of weights
    checkpoint = torch.load(WEIGHTS_PATH, map_location=device, weights_only=True)
    state_dict = checkpoint['state_dict'] if 'state_dict' in checkpoint else checkpoint
    net.load_state_dict(state_dict, strict=False)
    print(f"[+] Successfully loaded 2-Channel weights.")
except Exception as e:
    print(f"[!] Warning: Could not load weights. Proceeding with untrained model for testing. Error: {e}")

net.eval()
# 2. GRAD-CAM HOOKS
gradients = None
activations = None

def backward_hook(module, grad_input, grad_output):
    global gradients
    gradients = grad_output[0]

def forward_hook(module, input, output):
    global activations
    activations = output

# Target the final convolution of Layer 3
target_layer = net.model.layer3[-1].conv2[0]
target_layer.register_forward_hook(forward_hook)
target_layer.register_backward_hook(backward_hook)


# 3. VISUALIZATION HELPERS
def orient_slice(slice_data):
    return np.rot90(slice_data)

def plot_overlay(ax, bg_img, heatmap_img):
    ax.imshow(bg_img, cmap='gray')
    ax.imshow(heatmap_img, cmap='jet', alpha=0.45)
    ax.axis('off')

# 4. PROCESS PATIENTS

print(" 2. GENERATING 3D HEATMAPS ")
fig, axes = plt.subplots(len(MRI_PATHS), 3, figsize=(18, 18))
plt.subplots_adjust(wspace=0.05, hspace=0.05)

for row_idx, sample_mri_path in enumerate(MRI_PATHS):
    print(f"Processing Patient {row_idx + 1}/{len(MRI_PATHS)}...")

    if not os.path.exists(sample_mri_path):
        print(f"[!] File missing: {sample_mri_path}. Skipping.")
        continue

    img_data = np.load(sample_mri_path) # Shape: (2, 128, 128, 128)
    img_tensor = torch.tensor(img_data, dtype=torch.float32)

    # Add batch dimension -> (1, 2, 128, 128, 128)
    img_tensor = img_tensor.unsqueeze(0).to(device)

    # 4A. EXTRACT ACTIVATIONS
    net.zero_grad()
    # We pass through the CNN layers
    output = net(img_tensor)

    # We sum the output feature map to simulate a class backward pass
    loss = output.sum()
    loss.backward()

    pooled_grads = torch.mean(gradients, dim=[0, 2, 3, 4])
    curr_activations = activations.clone()

    for i in range(curr_activations.size(1)):
        curr_activations[:, i, :, :, :] *= pooled_grads[i]

    heatmap = torch.mean(curr_activations, dim=1).squeeze().cpu().detach().numpy()
    heatmap = np.maximum(heatmap, 0)
    if np.max(heatmap) > 0:
        heatmap /= np.max(heatmap)

    # Sharpening
    heatmap = np.power(heatmap, 5)
    if np.max(heatmap) > 0:
        heatmap /= np.max(heatmap)

    # 4B. RESIZE TO ORIGINAL SHAPE
    original_shape = (128, 128, 128)
    heatmap_resized = zoom(heatmap, (original_shape[0]/heatmap.shape[0],
                                     original_shape[1]/heatmap.shape[1],
                                     original_shape[2]/heatmap.shape[2]))

    # Isolate Primary Hotspot
    binary_mask = heatmap_resized > 0.05
    labeled_map, num_labels = label(binary_mask)

    if num_labels > 1:
        max_coords = np.unravel_index(np.argmax(heatmap_resized), heatmap_resized.shape)
        main_blob_label = labeled_map[max_coords]
        heatmap_resized = np.where(labeled_map == main_blob_label, heatmap_resized, 0.0)

    # 4C. AUTO-CENTER AND SLICE
    mri_3d = img_tensor.squeeze(0).cpu().numpy()
    if mri_3d.ndim == 4:
        mri_3d = mri_3d[0] # Channel 0: Structural MRI for background

    cam_3d = heatmap_resized
    center_x, center_y, center_z = np.unravel_index(np.argmax(cam_3d), cam_3d.shape)

    sag_mri, sag_cam = orient_slice(mri_3d[center_x, :, :]), orient_slice(cam_3d[center_x, :, :])
    cor_mri, cor_cam = orient_slice(mri_3d[:, center_y, :]), orient_slice(cam_3d[:, center_y, :])
    ax_mri, ax_cam = orient_slice(mri_3d[:, :, center_z]), orient_slice(cam_3d[:, :, center_z])

    # 4D. PLOT
    plot_overlay(axes[row_idx, 0], ax_mri, ax_cam)
    plot_overlay(axes[row_idx, 1], cor_mri, cor_cam)
    plot_overlay(axes[row_idx, 2], sag_mri, sag_cam)

    # Memory Cleanup
    del img_tensor, output, curr_activations, heatmap, heatmap_resized, mri_3d, cam_3d
    torch.cuda.empty_cache()
    gc.collect()

plt.savefig(OUTPUT_IMG, dpi=300, bbox_inches='tight', pad_inches=0.1)
print(f"\n[+] Finished! 3-Patient Grid saved to {OUTPUT_IMG}")